account/urls.py
from django.urls import path
from .views import *



urlpatterns = [
    path('sign_up',sign_up,name="sign_up"),
] 

car_factory/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('',include("account.urls")),
    path('',include('django.contrib.auth.urls'))

]

main_app/urls.py
from django.urls import path
from .views import *



app_name="main_app"
urlpatterns = [
    path("home",show_home_view,name="home"),
    path("buy_car_1",buy_car,name="buy_car"),
    path("buy_car_2",Buy_car_view,name="buy_car_2"),
    path("delete",delete_person_view,name="delete_person"),
    path("logout",logout_view,name="logout"),

]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


class User(AbstractUser):
    is_author   =models.BooleanField(default=False, verbose_name="وضعیت نویسندگی")
    special_user=models.DateTimeField(default=timezone.now,verbose_name="کاربر ویژه تا")


    def is_special_user(self):
        if self.special_user > timezone.now():
            return True
        else:
            return False


    is_special_user.boolean=True
    is_special_user.short_description="کاربر ویژه"

main_app/models.py
from django.db import models
from django.db.models import aggregates




class Person(models.Model):
    first_name =models.CharField(max_length=50)
    last_name  =models.CharField(max_length=50)
    father_name=models.CharField(max_length=50)
    age        =models.IntegerField()
    id_code    =models.IntegerField()


    def __str__(self):
        name=self.first_name+" "+self.last_name
        return name



class Car(models.Model):
    car_name=models.CharField(max_length=50)
    car_id  =models.IntegerField()
    color   =models.CharField(max_length=10)


    def __str__(self):
        return self.car_name

main_app/forms.py
from django import forms
from .models import *





class Person_form(forms.ModelForm):
    class Meta:
        model = Person
        fields="__all__"




class Buy_car_form(forms.ModelForm):
    class Meta:
        model = Car
        fields="__all__"

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required




def sign_up(request):
    context = {}
    form = UserCreationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect("main_app:home")
    context['form']=form
    return render(request,'registration/sign_up.html',context)

main_app/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect,render
from .forms import *
from .models import *


def show_home_view(request):
    return render(request,"main_app/home.html")




all_id=[]
def buy_car(request):
    form=Person_form(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            if form.cleaned_data['id_code'] in all_id:
                return HttpResponse("You did it before")
            else:
                all_id.append(form.cleaned_data['id_code'])
                form.save()
                return HttpResponse(all_id)

    context={
        'form':form,
    }
    return render(request,"main_app/buy_car.html",context)




def Buy_car_view(request):
    form=Buy_car_form(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            form.save()
    context={
        'form':form,
    }
    return render(request,"main_app/buy_car_2.html",context)




def delete_person_view(request):
    all_id=[]
    if request.method=="POST":
        roll_number = request.POST['delete_id_box']
        all_person=Person.objects.all()
        for person in all_person:
            all_id.append(person.id_code)


        obj=Person.objects.filter(id_code=roll_number)
        obj.delete()

        string="object deleted with this id ==> "+str(roll_number)
        return HttpResponse(string)



def logout_view(request):
    return render(request,"registration/logged_out.html")

templates/main_app/buy_car.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>خرید خودرو</title>
</head>
<body>

    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
    <input type="submit" value="Submit">
    </form>
    
</body>
</html>

templates/main_app/buy_car_2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>خرید خودرو فرم2</title>
</head>
<body>

    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
    <input type="submit" value="Submit">
    </form>
    
</body>
</html>

templates/main_app/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>خانه</title>
</head>
<body>
    <a href="{% url 'main_app:buy_car' %}">خرید خودرو</a><br>

{% if user.is_author %}
    <form method="POST" action="{% url 'main_app:delete_person' %}"><br>
        {% csrf_token %}
            <input name="delete_id_box" type="text" placeholder="enter id to delete person">
            <input type="submit" value="delete" style="color: rgb(236, 118, 118);">
    </form>
{% endif %}

</body>
</html>